#!/usr/bin/env bash
# bootstrap.sh — One-command SWARM setup
# ═══════════════════════════════════════════════════════════════════════════════
# Usage:
#   ./bootstrap.sh           # interactive setup
#   ./bootstrap.sh --auto    # non-interactive (uses defaults)
#   SWARM_ROOT=/opt/swarm ./bootstrap.sh --auto
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="${SWARM_ROOT:-$SCRIPT_DIR}"
AUTO=false
[[ "${1:-}" == "--auto" ]] && AUTO=true

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "  SWARM Bootstrap"
echo "  Root: $SWARM_ROOT"
echo "═══════════════════════════════════════════════════════════════════════════════"

# ── 1. Python version check ───────────────────────────────────────────────────
PYTHON="${PYTHON:-python3}"
PYVER=$($PYTHON -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
REQUIRED="3.11"
if [[ "$(printf '%s\n' "$REQUIRED" "$PYVER" | sort -V | head -n1)" != "$REQUIRED" ]]; then
    echo "✗ Python $PYVER found, but >= $REQUIRED is required."
    exit 1
fi
echo "✓ Python $PYVER"

# ── 2. Virtual environment ────────────────────────────────────────────────────
VENV_DIR="$SWARM_ROOT/.venv"
if [[ ! -f "$VENV_DIR/bin/python" ]]; then
    echo "→ Creating venv at $VENV_DIR ..."
    $PYTHON -m venv "$VENV_DIR"
fi
echo "✓ Venv ready"

PIP="$VENV_DIR/bin/pip"
PYTHON_VENV="$VENV_DIR/bin/python"

# ── 3. Dependencies ───────────────────────────────────────────────────────────
if [[ -f "$SWARM_ROOT/requirements-lock.txt" ]]; then
    echo "→ Installing from requirements-lock.txt (pinned) ..."
    "$PIP" install -q -r "$SWARM_ROOT/requirements-lock.txt"
else
    echo "→ Installing from requirements.txt ..."
    "$PIP" install -q -r "$SWARM_ROOT/requirements.txt"
fi

# ── 4. Environment file ───────────────────────────────────────────────────────
ENV_FILE="$SWARM_ROOT/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    if $AUTO; then
        SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || $PYTHON_VENV -c 'import secrets; print(secrets.token_hex(32))')
        cat > "$ENV_FILE" <<EOF
# Auto-generated by bootstrap.sh — $(date -Iseconds)
SWARM_ROOT=$SWARM_ROOT
SWARM_ENV=prod
SECRET_KEY=$SECRET_KEY
FLASK_ENV=production
EOF
    else
        echo ""
        echo "Create .env file? [Y/n]"
        read -r ans
        if [[ "$ans" != "n" && "$ans" != "N" ]]; then
            SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || $PYTHON_VENV -c 'import secrets; print(secrets.token_hex(32))')
            cat > "$ENV_FILE" <<EOF
# Auto-generated by bootstrap.sh — $(date -Iseconds)
SWARM_ROOT=$SWARM_ROOT
SWARM_ENV=prod
SECRET_KEY=$SECRET_KEY
FLASK_ENV=production
EOF
            echo "✓ .env created (edit it to add API keys)"
        fi
    fi
else
    echo "✓ .env already exists"
fi

# ── 5. Database init ──────────────────────────────────────────────────────────
DB_PATH="$SWARM_ROOT/swarm_memory.db"
if [[ ! -f "$DB_PATH" ]]; then
    echo "→ Initialising SQLite database ..."
    cd "$SWARM_ROOT"
    SWARM_ROOT="$SWARM_ROOT" "$PYTHON_VENV" -c "
import sys, os
sys.path.insert(0, os.environ['SWARM_ROOT'])
from utils.db._schema import init_db
init_db()
print('Database initialised')
" || true
else
    echo "✓ Database exists"
fi

# ── 6. Pre-commit hooks ───────────────────────────────────────────────────────
if [[ -f "$SWARM_ROOT/scripts/install-hooks.sh" ]]; then
    echo "→ Installing git hooks ..."
    bash "$SWARM_ROOT/scripts/install-hooks.sh" || true
fi

# ── 7. Health check ───────────────────────────────────────────────────────────
echo ""
echo "→ Running health check ..."
cd "$SWARM_ROOT"
SWARM_ROOT="$SWARM_ROOT" "$PYTHON_VENV" -m ops.bullshit_detector 2>/dev/null || true

echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "  Bootstrap complete."
echo ""
echo "  Start the server:"
echo "    cd $SWARM_ROOT && .venv/bin/python frontend/terminal.py"
echo ""
echo "  Or with systemd:"
echo "    sudo cp swarm-*.service /etc/systemd/system/"
echo "    sudo systemctl daemon-reload"
echo "    sudo systemctl enable --now swarm-terminal"
echo ""
echo "  Visit: http://localhost:5050"
echo "═══════════════════════════════════════════════════════════════════════════════"
