"""
scheduler.py — Seven's Swarm Scheduler
Basic proactive tasks. Runs daily digest, snooze checks, etc.
"""

import time
from datetime import datetime, timedelta
import sys
sys.path.insert(0, '/home/seven/swarm')
sys.path.insert(0, '/home/seven/swarm/utils')

from database import get_digest_stats, get_due_snoozed, mark_snooze_fired, get_overdue_tickets, get_connection
from sandpits import list_proposals


def list_tasks():
    """Return all enabled scheduled tasks from the DB."""
    with get_connection() as conn:
        rows = conn.execute(
            'SELECT id, name, schedule, action_type, action_data, next_run FROM scheduled_tasks WHERE enabled=1 ORDER BY id'
        ).fetchall()
    return [{'id': r[0], 'name': r[1], 'schedule': r[2], 'action_type': r[3], 'action_data': r[4], 'next_run': r[5]} for r in rows]


def add_task(name, schedule, action_type, action_data, created_by='system'):
    """Add a scheduled task to the DB. Ignores if name already exists."""
    with get_connection() as conn:
        conn.execute(
            'INSERT OR IGNORE INTO scheduled_tasks (name, schedule, action_type, action_data, created_by) VALUES (?, ?, ?, ?, ?)',
            (name, schedule, action_type, action_data, created_by)
        )


def _advance_next_run(name):
    """Advance next_run for a task after it fires. Parses 'daily HH:MM' schedules."""
    with get_connection() as conn:
        row = conn.execute(
            'SELECT schedule FROM scheduled_tasks WHERE name=?', (name,)
        ).fetchone()
        if not row:
            return
        schedule = (row[0] or '').strip()
        now = datetime.now()
        next_run = None
        if schedule.lower().startswith('daily '):
            try:
                hhmm = schedule.split(None, 1)[1]
                h, m = int(hhmm.split(':')[0]), int(hhmm.split(':')[1])
                candidate = now.replace(hour=h, minute=m, second=0, microsecond=0)
                if candidate <= now:
                    candidate += timedelta(days=1)
                next_run = candidate.strftime('%Y-%m-%d %H:%M:%S')
            except Exception:
                pass
        if next_run:
            conn.execute(
                'UPDATE scheduled_tasks SET last_run=?, next_run=? WHERE name=?',
                (now.strftime('%Y-%m-%d %H:%M:%S'), next_run, name)
            )


def run_daily_brief():
    """Generate a Ghost Brief and email it to Ghost."""
    try:
        sys.path.insert(0, '/home/seven/swarm/lib/email')
        from brief_engine import generate_brief
        brief = generate_brief(trigger='daily_schedule')
        if not brief:
            print('[Scheduler] Daily brief: generation failed — check Claude API key')
            return
        from email_handler import send_reply
        from config import GHOST_EMAIL
        send_reply(
            to_address=GHOST_EMAIL,
            subject=f'[Swarm] Ghost Brief — {datetime.now().strftime("%A %d %B")}',
            body=brief['content'] + f'\r\n\r\n---\nGenerated by Nine · {brief["tokens_used"]} tokens'
        )
        print(f'[Scheduler] Daily brief sent — {brief["tokens_used"]} tokens')
        _advance_next_run('daily_brief')
    except Exception as e:
        print(f'[Scheduler] Daily brief error: {e}')


def run_daily_digest():
    stats = get_digest_stats()
    proposals = len(list_proposals())
    overdue = len(get_overdue_tickets(hours=4))

    print(f"\n[Scheduler] Daily Digest — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"  Tickets opened today: {stats['opened']}")
    print(f"  Tickets closed today: {stats['closed']}")
    print(f"  Open tickets: {stats['open']}")
    print(f"  Overdue tickets (>4h): {overdue}")
    print(f"  Pending proposals: {proposals}")
    print(f"  Duck checks: YES {stats['duck_yes']} | NO {stats['duck_no']}")
    if stats['top_tags']:
        print("  Top tags:", [t[0] for t in stats['top_tags']])
    _advance_next_run('daily_digest')

def check_snoozed():
    due = get_due_snoozed()
    for snooze in due:
        print(f"[Scheduler] Waking snoozed ticket {snooze['ticket_number']}")
        mark_snooze_fired(snooze['id'])

def disable_task(task_id):
    """Disable a scheduled task by numeric ID."""
    with get_connection() as conn:
        conn.execute('UPDATE scheduled_tasks SET enabled=0 WHERE id=?', (task_id,))


def parse_schedule_command(line):
    """
    Parse a SCHEDULE command from an email/message line.
    Format: SCHEDULE <schedule> <ACTION_TYPE> <data>
    Examples:
      SCHEDULE daily 09:00 QUESTION What is today's news?
      SCHEDULE daily 18:00 SHELL df -h

    Returns (name, schedule, action_type, action_data) or None if unparseable.
    """
    parts = line.strip().split(None, 3)
    # Expect: SCHEDULE  <word> <HH:MM> <ACTION> <data>   (4+ parts after split)
    # Or:     SCHEDULE  <word> <ACTION> <data>            (3+ parts)
    if len(parts) < 4:
        return None
    # parts[0] is 'SCHEDULE'
    # Try 'daily HH:MM' as the schedule field
    if parts[1].lower() == 'daily' and ':' in parts[2]:
        schedule = f'daily {parts[2]}'
        remainder = parts[3] if len(parts) > 3 else ''
        rem_parts = remainder.split(None, 1)
        if not rem_parts:
            return None
        action_type = rem_parts[0].upper()
        action_data = rem_parts[1] if len(rem_parts) > 1 else ''
    else:
        # Fallback: parts[1]=action_type, rest=data, no schedule
        return None
    name = f'{action_type.lower()}_{schedule.replace(" ", "_").replace(":", "")}'
    return (name, schedule, action_type, action_data)


def check_due():
    """Check for scheduled tasks that are due and run them."""
    import subprocess
    from datetime import datetime
    now_str = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT id, name, action_type, action_data FROM scheduled_tasks
               WHERE enabled=1 AND (next_run IS NULL OR next_run <= ?)""",
            (now_str,)
        ).fetchall()

    for row in rows:
        task_id, name, action_type, action_data = row[0], row[1], row[2], row[3]
        try:
            if action_type == 'SHELL':
                subprocess.Popen(action_data, shell=True)
                print(f'[Scheduler] Fired SHELL task #{task_id}: {action_data[:60]}')
            elif action_type in ('QUESTION', 'BRIEF'):
                # Delegate to brief engine for brief tasks; ignore questions (handled by listener)
                if 'brief_engine' in (action_data or ''):
                    subprocess.Popen(action_data, shell=True)
                    print(f'[Scheduler] Fired BRIEF task #{task_id}')
            # Advance next_run for this task
            _advance_next_run(name)
        except Exception as e:
            print(f'[Scheduler] Task #{task_id} ({name}) error: {e}')


def main_loop():
    print("Scheduler started — checking every 60 seconds (press Ctrl+C to stop)")
    while True:
        try:
            check_due()
            check_snoozed()
            run_daily_digest()
            time.sleep(60)
        except KeyboardInterrupt:
            print("\nScheduler stopped.")
            break
        except Exception as e:
            print(f"[Scheduler Error] {e}")
            time.sleep(60)

if __name__ == '__main__':
    main_loop()