"""
agents/gemma/gemma_agent.py — Gemma3
Generated by Swarm bootstrap. Customise as needed.
"""
import logging, sys
sys.path.insert(0, '/home/seven/swarm/utils')
sys.path.insert(0, '/home/seven/swarm/frontend')
logger = logging.getLogger('seven.gemma')
AGENT_NAME = 'gemma'

def _build_context(message):
    from database import get_connection, get_agent_memory
    lines = ['=== Governance rules (ALM) ===',
             'Mutating changes require approved work proposals.',]
    conn = get_connection()
    try:
        queued = conn.execute("SELECT COUNT(*) FROM queue WHERE status='queued'").fetchone()[0]
        lines.append(f'Queue: {queued} queued')
    finally:
        conn.close()
    mems = get_agent_memory(AGENT_NAME, query=message, limit=5)
    if mems:
        lines.append(f"\n=== {AGENT_NAME.capitalize()}'s memory ===")
        for m in mems:
            m = dict(m)
            lines.append(f"[{str(m.get('created_at',''))[:16]}] {m.get('subject','')}: {str(m.get('content',''))[:200]}")
    return '\n'.join(lines)

def chat(message, conversation_history=None, stage_cb=None):
    def _emit(t):
        if callable(stage_cb):
            try: stage_cb(t, None)
            except Exception: pass
    try:
        from openai import OpenAI
    except ImportError:
        return '[gemma] openai package not installed', 0
    from config import OPENAI_API_KEY
    const_mod = __import__('config', fromlist=['GEMMA_SYSTEM_PROMPT'])
    system_prompt = getattr(const_mod, 'GEMMA_SYSTEM_PROMPT', 'Gemma3 — Ghost Layer agent.')
    api_key = OPENAI_API_KEY
    if not api_key:
        return '[gemma] OPENAI_API_KEY not configured', 0
    _emit('loading memory')
    context = _build_context(message)
    messages = [{"role": "system", "content": system_prompt + '\n\n' + context}]
    if conversation_history:
        messages.extend(conversation_history[-10:])
    messages.append({"role": "user", "content": message})
    try:
        _emit('sending request')
    client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model='gemma3:latest', messages=messages, max_tokens=2048)
        answer = response.choices[0].message.content
        tokens = response.usage.total_tokens if response.usage else 0
        _emit('persisting memory')
        try:
            from database import save_agent_memory
            save_agent_memory(agent_name=AGENT_NAME, subject=str(message or '')[:100],
                              content=answer, tags='chat,shared-thread', importance=7, source='terminal_chat')
        except Exception: pass
        logger.info(f'[Gemma3] tokens={tokens}')
        return answer, tokens
    except Exception as e:
        msg = str(e)
        logger.error(f'[Gemma3] error: {msg}')
        if '401' in msg or 'auth' in msg.lower(): return '[gemma] API key invalid.', 0
        if '429' in msg or 'rate' in msg.lower(): return f'[gemma] Rate limit hit.', 0
        return f'[gemma] error: {msg}', 0
