#!/usr/bin/env python3
"""
scripts/generate_env.py — Generate .env.template from required env vars (D.4.3)
═══════════════════════════════════════════════════════════════════════════════
Generates a documented .env.template and validates existing .env files.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

ENV_TEMPLATE = {
    # Core
    'SWARM_ROOT': ('Path to swarm repository root', '/home/user/swarm'),
    'SWARM_ENV': ('Environment: prod, dev, uat', 'prod'),
    'SWARM_NAME': ("Display name for this swarm node", "Seven's Swarm"),
    'SWARM_DB_PATH': ('Path to SQLite database', ''),

    # API Keys (required for agent communication)
    'AGENT_API_KEY': ('API key for inter-agent calls', ''),
    'GROQ_API_KEY': ('Groq API key for cloud agents', ''),
    'TAVILY_API_KEY': ('Tavily search API key', ''),
    'GITHUB_TOKEN': ('GitHub personal access token', ''),

    # Multi-node
    'SWARM_NODE_NAME': ('Display name for this node', 'primary'),
    'SWARM_NODE_URL': ('URL where this node is reachable', 'http://localhost:5050'),
    'SWARM_NODE_API_KEY': ('API key for node-to-node auth', ''),

    # Event relay
    'SWARM_RELAY_TOPICS': ('Comma-separated topics to relay', 'proposal.created,proposal.status_changed,knowledge.new,tool.registered'),

    # Performance
    'SWARM_RATE_LIMIT': ('Max API requests per minute per IP', '60'),
    'SWARM_MAX_REQUEST_MB': ('Max request body size in MB', '1'),
}


def generate_template(output_path=None):
    """Generate .env.template with documented entries."""
    if output_path is None:
        output_path = os.path.join(os.environ.get('SWARM_ROOT', '.'), '.env.template')

    lines = [
        '# Seven\'s Swarm — Environment Template',
        '# Generated by scripts/generate_env.py',
        '# Copy to .env and fill in values',
        '',
    ]

    for key, (desc, default) in ENV_TEMPLATE.items():
        lines.append(f'# {desc}')
        if default:
            lines.append(f'{key}={default}')
        else:
            lines.append(f'# {key}=')
        lines.append('')

    content = '\n'.join(lines)
    with open(output_path, 'w') as f:
        f.write(content)
    return output_path


def validate_env(env_path=None):
    """Validate an .env file against the template.
    Returns (missing: list, extra: list).
    """
    if env_path is None:
        env_path = os.path.join(os.environ.get('SWARM_ROOT', '.'), '.env.agents')

    expected = set(ENV_TEMPLATE.keys())
    found = set()

    if os.path.isfile(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key = line.split('=', 1)[0].strip()
                    found.add(key)

    missing = expected - found
    extra = found - expected
    return sorted(missing), sorted(extra)


if __name__ == '__main__':
    path = generate_template()
    print(f'Generated: {path}')

    missing, extra = validate_env()
    if missing:
        print(f'\nMissing vars in .env: {", ".join(missing)}')
    if extra:
        print(f'\nExtra vars in .env (not in template): {", ".join(extra)}')
    if not missing and not extra:
        print('\n.env is in sync with template.')
