#!/usr/bin/env python3
"""
scripts/update_docs.py — Auto-generate reference docs from the running code.

Produces:
  - docs/api/endpoints.md        — route index from Flask blueprints
  - docs/reference/shortcuts.md  — keyboard shortcuts extracted from UI

Callable from CLI:
    python3 scripts/update_docs.py

Also invoked automatically by the `landscape_refresh` Fridays task and via the
Vortex post-proposal hook, so the reference docs stay in sync without manual
intervention.
"""
from __future__ import annotations

import datetime
import os
import re

SWARM_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLUEPRINTS_DIR = os.path.join(SWARM_ROOT, 'frontend', 'blueprints')
TERMINAL_BASE = os.path.join(SWARM_ROOT, 'frontend', 'templates', 'terminal_base.html')
SPOTLIGHT_JS = os.path.join(SWARM_ROOT, 'frontend', 'static', 'js', 'views', 'spotlight.js')
INIT_JS = os.path.join(SWARM_ROOT, 'frontend', 'static', 'js', 'core', 'init.js')

API_OUT = os.path.join(SWARM_ROOT, 'docs', 'api', 'endpoints.md')
SHORTCUTS_OUT = os.path.join(SWARM_ROOT, 'docs', 'reference', 'shortcuts.md')

_ROUTE_RE = re.compile(r"@(\w+)_bp\.route\(\s*['\"]([^'\"]+)['\"](?:[^)]*methods\s*=\s*\[([^\]]+)\])?")


def _scan_blueprints() -> list[dict]:
    routes: list[dict] = []
    if not os.path.isdir(BLUEPRINTS_DIR):
        return routes
    for fname in sorted(os.listdir(BLUEPRINTS_DIR)):
        if not fname.endswith('.py') or fname.startswith('_'):
            continue
        fpath = os.path.join(BLUEPRINTS_DIR, fname)
        try:
            with open(fpath, encoding='utf-8', errors='ignore') as fh:
                text = fh.read()
        except Exception:
            continue
        for m in _ROUTE_RE.finditer(text):
            bp, path, methods = m.group(1), m.group(2), m.group(3)
            methods_list = (
                [x.strip().strip("'\"") for x in methods.split(',')] if methods else ['GET']
            )
            routes.append({
                'blueprint': bp,
                'path': path,
                'methods': methods_list,
                'file': fname,
            })
    return routes


def _write_api_doc(routes: list[dict]) -> str:
    os.makedirs(os.path.dirname(API_OUT), exist_ok=True)
    by_bp: dict[str, list[dict]] = {}
    for r in routes:
        by_bp.setdefault(r['blueprint'], []).append(r)
    ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        '# API Endpoints',
        '',
        f'_Auto-generated by `scripts/update_docs.py` — last updated {ts}._',
        '',
        f'Total routes: **{len(routes)}** across **{len(by_bp)}** blueprints.',
        '',
    ]
    for bp in sorted(by_bp):
        lines.append(f'## `{bp}`')
        lines.append('')
        lines.append('| Method | Path | Source |')
        lines.append('|--------|------|--------|')
        for r in sorted(by_bp[bp], key=lambda x: x['path']):
            methods = ', '.join(r['methods'])
            lines.append(f"| {methods} | `{r['path']}` | `{r['file']}` |")
        lines.append('')
    with open(API_OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))
    return API_OUT


# --- Keyboard shortcuts ---------------------------------------------------

_KBD_ROW_RE = re.compile(
    r"<span>([^<]+)</span>\s*<kbd[^>]*>([^<]+)</kbd>",
    re.IGNORECASE,
)


def _extract_shortcuts() -> list[tuple[str, str]]:
    """Scan the static shortcuts-help-modal block for <span>label</span><kbd>keys</kbd> rows."""
    try:
        with open(TERMINAL_BASE, encoding='utf-8', errors='ignore') as fh:
            html = fh.read()
    except Exception:
        return []
    # Slice just the modal
    start = html.find('id="shortcuts-help-modal"')
    if start < 0:
        return []
    end = html.find('</div>\n</div>', start)
    block = html[start:end] if end > 0 else html[start:]
    pairs: list[tuple[str, str]] = []
    for m in _KBD_ROW_RE.finditer(block):
        label = re.sub(r'\s+', ' ', m.group(1)).strip()
        keys = re.sub(r'\s+', ' ', m.group(2)).strip()
        if label and keys and (label, keys) not in pairs:
            pairs.append((label, keys))
    return pairs


def _extract_spotlight_commands() -> list[tuple[str, str]]:
    try:
        with open(SPOTLIGHT_JS, encoding='utf-8', errors='ignore') as fh:
            text = fh.read()
    except Exception:
        return []
    # Lines like: { label: 'Chat', icon: _SP_SVG.chat, hint: 'Ctrl+J', ...}
    entries = []
    for m in re.finditer(
        r"\{\s*label:\s*'([^']+)'[^}]*?hint:\s*'([^']*)'",
        text,
    ):
        label, hint = m.group(1), m.group(2)
        entries.append((label, hint or '—'))
    return entries


def _write_shortcuts_doc() -> str:
    os.makedirs(os.path.dirname(SHORTCUTS_OUT), exist_ok=True)
    pairs = _extract_shortcuts()
    spot = _extract_spotlight_commands()
    ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        '# Keyboard Shortcuts & Spotlight Reference',
        '',
        f'_Auto-generated by `scripts/update_docs.py` — last updated {ts}._',
        '',
        '## Spotlight (Ctrl+Space)',
        '',
        'The fastest way around Fridays. One search bar searches **commands**, '
        '**docs**, **knowledge base**, **tickets**, **proposals**, '
        '**conversations** and **memory**.',
        '',
        '- Open anywhere: `Ctrl+Space`',
        '- Navigate: `↑` / `↓`',
        '- Open result: `Enter`',
        '- Close: `Esc`',
        '',
        '### Spotlight commands',
        '',
        '| Command | Shortcut |',
        '|---------|----------|',
    ]
    for label, hint in spot:
        lines.append(f'| {label} | `{hint}` |')
    lines.append('')
    lines.append('## Global shortcuts')
    lines.append('')
    lines.append('| Action | Keys |')
    lines.append('|--------|------|')
    for label, keys in pairs:
        lines.append(f'| {label} | `{keys}` |')
    lines.append('')
    lines.append('> To view this reference in-app, press `?` anywhere.')
    lines.append('')
    with open(SHORTCUTS_OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))
    return SHORTCUTS_OUT


def generate() -> dict:
    """Run all doc generators. Returns a summary dict."""
    routes = _scan_blueprints()
    api_path = _write_api_doc(routes)
    shortcuts_path = _write_shortcuts_doc()
    return {
        'routes': len(routes),
        'api_doc': os.path.relpath(api_path, SWARM_ROOT),
        'shortcuts_doc': os.path.relpath(shortcuts_path, SWARM_ROOT),
    }


if __name__ == '__main__':
    summary = generate()
    print(
        f"Updated: {summary['api_doc']} ({summary['routes']} routes), "
        f"{summary['shortcuts_doc']}"
    )
